resource_types:
- name: pull-request
  type: registry-image
  source:
    repository: aoldershaw/github-pr-resource

resources:
- name: pull-request
  type: pull-request
  check_every: 30s
  webhook_token: ((github-webhook-token))
  source:
    repository: tracim/tracim
    access_token: ((github-access-token))
    number: ((number))

jobs:
- name: reconfigure-self
  plan:
  - get: pull-request
    trigger: true
  - set_pipeline: self
    file: pull-request/concourse/pipelines/pull-request.yml
- name: test
  plan:
  - get: pull-request
    trigger: true
  - put: pull-request-status
    resource: pull-request
    params:
      path: pull-request
      status: pending
    get_params:
      skip_download: true
  - task: backend-lint
    file: pull-request/concourse/tasks/test.yml
    input_mapping:
      tracim: pull-request
    vars:
      path: tracim/concourse/scripts/backend-lint
      args: []
  on_success:
    put: pull-request
    params:
      path: pr
      status: success
    get_params:
      skip_download: true
  on_failure:
    put: pull-request
    params:
      path: pr
      status: failure
    get_params:
      skip_download: true
  on_error:
    put: pull-request
    params:
      path: pr
      status: error
    get_params:
      skip_download: true
  on_abort:
    put: pull-request
    params:
      path: pr
      status: error
    get_params:
      skip_download: true
