_update_status: &_update_status
  resource: pull-request
  get_params:
    skip_download: true

_update_status_params: &_update_status_params
  path: pull-request

_update_pull_request_status_failures: &_update_pull_request_status_failures
  on_failure:
    put: pull-request-failure
    <<: *_update_status
    params:
      <<: *_update_status_params
      status: failure
  on_error:
    put: pull-request-error
    <<: *_update_status
    params:
      <<: *_update_status_params
      status: error
  on_abort:
    put: pull-request-abort
    <<: *_update_status
    params:
      <<: *_update_status_params
      status: error

resource_types:
- name: pull-request
  type: registry-image
  source:
    repository: aoldershaw/github-pr-resource

resources:
- name: pull-request
  type: pull-request
  check_every: 30s
  # TODO - S.G. - 2021/08/02
  # The token is not used as one webhook would have to be created PER PR in github.
  # This could be automated, but is not so easy.
  webhook_token: ((github-webhook-token))
  source:
    repository: tracim/tracim
    access_token: ((github-access-token))
    number: ((number))

jobs:
- name: reconfigure-self
  plan:
  - get: pull-request
    trigger: true
  - put: pull-request-pending
    <<: *_update_status
    params:
      <<: *_update_status_params
      status: pending
  - set_pipeline: self
    file: pull-request/concourse/pipelines/pull-request.yml
    vars:
      github-webhook-token: ((github-webhook-token))
      github-access-token: ((github-access-token))
- name: backend-tests
  plan:
  - get: pull-request
    passed: [reconfigure-self]
    trigger: true
  # - task: backend-lint
  #   file: pull-request/concourse/tasks/test.yml
  #   input_mapping:
  #     tracim: pull-request
  #   vars:
  #     python_version: "3.6.14"
  #     path: concourse/scripts/backend-lint
  #     database: ""
  - across:
    - var: python_version
      values: [] # ["3.5.10" , "3.6.14", "3.7.11"]
      max_in_flight: all
    task: backend-quick-tests_((.:python_version))
    # needed for docker during tests
    privileged: true
    file: pull-request/concourse/tasks/test.yml
    input_mapping:
      tracim: pull-request
    vars:
      python_version: ((.:python_version))
      path: concourse/scripts/backend-quick-tests
      database: sqlite
  - across:
    - var: database
      values: [] # ["sqlite", "postgresql", "mysql", "mariadb"]
      max_in_flight: all
    task: backend-full-tests_((.:database))
    # needed for docker during tests
    privileged: true
    file: pull-request/concourse/tasks/test.yml
    input_mapping:
      tracim: pull-request
    vars:
      python_version: "3.6.14"
      path: concourse/scripts/backend-full-tests
      database: ((.:database))
  <<: *_update_pull_request_status_failures

- name: frontend-tests
  plan:
    - get: pull-request
      passed: [reconfigure-self]
      trigger: true
    - task: frontend-unit-tests
      file: pull-request/concourse/tasks/test.yml
      input_mapping:
        tracim: pull-request
      vars:
        path: concourse/scripts/frontend-unit-tests
        python_version: "3.6.14"
        database: ""
  <<: *_update_pull_request_status_failures

- name: end-to-end-tests
  plan:
    - get: pull-request
      passed: [backend-tests, frontend-tests]
      trigger: true
    - task: end-to-end-cypress-tests
      # needed for docker during tests
      privileged: true
      file: pull-request/concourse/tasks/test.yml
      input_mapping:
        tracim: pull-request
      vars:
        path: concourse/scripts/end-to-end-cypress-tests
        python_version: "3.6.14"
        database: ""
  on_success:
    put: pull-request-success
    <<: *_update_status
    params:
      <<: *_update_status_params
      status: success
  <<: *_update_pull_request_status_failures
