resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
- name: pull-request
  type: pull-request
  icon: github
  # No need to check frequently as the resource will be checked by the github webhook
  check_every: never
  webhook_token: ((tracim:github-webhook-token))
  source:
    # Do not launch the CI for Tracim's github forks
    disable_forks: true
    repository: tracim/tracim
    access_token: ((tracim:github-access-token))

- name: develop
  type: git
  icon: github
  check_every: 24h
  source:
    uri: https://github.com/tracim/tracim.git
    branch: develop

jobs:
# Update this pipeline each time it is executed
- name: configure-self-from-pr
  plan:
    - get: pull-request
      trigger: true
    - set_pipeline: self
      file: pull-request/pipelines/tracim.yml
- name: configure-self-from-develop
  plan:
    - get: develop
      trigger: true
    - set_pipeline: self
      file: develop/pipelines/tracim.yml
# Update the tests pipeline when executed
- name: configure-tests-from-pr
  plan:
    - get: pull-request
      trigger: true
      passed: [configure-self-from-pr]
    - set_pipeline: tracim-tests
      file: pull-request/pipelines/tests.yml
- name: configure-tests-from-develop
  plan:
    - get: develop
      trigger: true
      passed: [configure-self-from-develop]
    - set_pipeline: tracim-tests
      file: develop/pipelines/tests.yml
