resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: aoldershaw/github-pr-resource

resources:
- name: pull-requests
  type: pull-request
  icon: github
  # No need to check as the resource will be checked by the github webhook
  check_every: never
  webhook_token: ((tracim:github-webhook-token))
  source:
    # Do not launch the CI for Tracim's github forks
    disable_forks: true
    repository: tracim/tracim
    access_token: ((tracim:github-access-token))

# - name: develop
#   type: git
#   icon: github
#   check_every: 24h
#   source:
#     uri: https://github.com/tracim/tracim.git
#     branch: develop

jobs:
# Manage the PR pipelines
- name: reconfigure-prs
  plan:
    - load_var: pull_requests
      file: pull-requests/prs.json
    - across:
        - var: pr
          values: ((.:pull_requests))
          max_in_flight: all
      set_pipeline: prs
      file: pull-requests/pipelines/pull-request.yml
      instance_vars:
        number: ((.:pr.number))
