# This pipeline handles the (re-) configuration of pull requests and xxx builds
resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: aoldershaw/github-pr-resource

resources:
- name: pull-requests
  type: pull-request
  icon: github
  # No need to check as the resource will be checked by the github webhook
  check_every: never
  webhook_token: ((github-webhook-token))
  source:
    # Do not launch the CI for Tracim's github forks
    disable_forks: true
    repository: tracim/tracim
    access_token: ((github-access-token))
- name: pipelines-and-tasks
  type: git
  icon: github
  check_every: 24h
  source:
    uri: https://github.com/tracim/tracim.git
    # FIXME: this should be develop when the initial PR is accepted.
    branch: misc/4828__concourse_pipeline
    paths:
      - concourse

jobs:
- name: reconfigure-prs
  plan:
    - in_parallel:
        - get: pull-requests
          trigger: true
        - get: pipelines-and-tasks
          trigger: true
    - load_var: pull_requests
      file: pull-requests/prs.json
    - across:
      - var: pr
        values: ((.:pull_requests))
        max_in_flight: all
      set_pipeline: tracim-pull-requests
      file: pipelines-and-tasks/concourse/pipelines/pull-request.yml
      instance_vars:
        number: ((.:pr.number))
      vars:
        github-webhook-token: ((github-webhook-token))
        github-access-token: ((github-access-token))
