# This pipeline handles the configuration of pull requests and regular (develop, …) CI pipelines
resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: aoldershaw/github-pr-resource

resources:
  - name: pull-requests
    type: pull-request
    icon: github
    # No need to check as the resource will be checked by the github webhook
    check_every: never
    webhook_token: ((github-webhook-token))
    source:
      # Do not launch the CI for Tracim's github forks
      disable_forks: true
      repository: tracim/tracim
      access_token: ((github-access-token))

  - name: pipelines-and-tasks
    type: git
    icon: github
    check_every: 24h
    source:
      uri: https://github.com/tracim/tracim.git
      branch: misc/4886__branch_pipeline
      paths:
        - concourse

jobs:
  - name: configure-pull-requests
    plan:
      - in_parallel:
        - get: pull-requests
          trigger: true
        - get: pipelines-and-tasks
          trigger: true
      - load_var: pull_requests
        file: pull-requests/prs.json
      - across:
        - var: pr
          values: ((.:pull_requests))
          max_in_flight: all
        set_pipeline: tracim-pull-requests
        file: pipelines-and-tasks/concourse/pipelines/pull-request-bootstrap.yml
        instance_vars:
          number: ((.:pr.number))
        vars:
          github-webhook-token: ((github-webhook-token))
          github-access-token: ((github-access-token))
          concourse-bot-user: ((concourse-bot-user))
          concourse-bot-password: ((concourse-bot-password))
          docker-registry: ((docker-registry))

  - name: configure-develop
    plan:
      - get: pipelines-and-tasks
        trigger: true
      - set_pipeline: tracim-branches
        file: pipelines-and-tasks/concourse/pipelines/branch-bootstrap.yml
        instance_vars:
          branch: misc/4886__branch_pipeline
        vars:
          github-webhook-token: ((github-webhook-token))
          github-access-token: ((github-access-token))
          concourse-bot-user: ((concourse-bot-user))
          concourse-bot-password: ((concourse-bot-password))
          docker-registry: ((docker-registry))
