export const TimelineDebugData = [{
  is_deleted: false,
  is_archived: false,
  sub_content_types: ['thread', 'file', 'folder', 'html-document'],
  raw_content: '',
  status: 'open',
  content_id: 22,
  show_in_ui: true,
  comment_ids: [],
  parent_id: null,
  created: '21/06/2018 à 15:12:40',
  slug: 'bonjour',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  content_type: 'html-document',
  workspace_id: 1,
  revision_id: 22,
  label: 'bonjour?',
  timelineType: 'revision',
  commentList: [],
  number: 1
}, {
  is_deleted: false,
  is_archived: false,
  sub_content_types: ['thread', 'file', 'folder', 'html-document'],
  raw_content: 'bonjour.',
  status: 'open',
  content_id: 22,
  show_in_ui: true,
  comment_ids: [31, 32],
  parent_id: null,
  created: '28/06/2018 à 15:13:26',
  slug: 'bonjour',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  content_type: 'html-document',
  workspace_id: 1,
  revision_id: 30,
  label: 'bonjour?',
  timelineType: 'revision',
  commentList: [{
    timelineType: 'comment',
    raw_content: 'testest',
    author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
    parent_id: 22,
    created: '28/06/2018 à 15:13:42',
    content_id: 31
  }, {
    timelineType: 'comment',
    raw_content: 'bravo.',
    author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
    parent_id: 22,
    created: '28/06/2018 à 15:36:02',
    content_id: 32
  }],
  number: 2
}, {
  timelineType: 'comment',
  raw_content: 'testest',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  parent_id: 22,
  created: '28/06/2018 à 15:13:42',
  content_id: 31,
  customClass: ''
}, {
  timelineType: 'comment',
  raw_content: 'bravo.',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  parent_id: 22,
  created: '28/06/2018 à 15:36:02',
  content_id: 32,
  customClass: ''
}, {
  is_deleted: false,
  is_archived: false,
  sub_content_types: ['thread', 'file', 'folder', 'html-document'],
  raw_content: 'bonjour.\nmerci.',
  status: 'open',
  content_id: 22,
  show_in_ui: true,
  comment_ids: [33],
  parent_id: null,
  created: '28/06/2018 à 15:43:51',
  slug: 'bonjour',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  content_type: 'html-document',
  workspace_id: 1,
  revision_id: 33,
  label: 'bonjour?',
  timelineType: 'revision',
  commentList: [{
    timelineType: 'comment',
    raw_content: 'woot',
    author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
    parent_id: 22,
    created: '28/06/2018 à 15:44:00',
    content_id: 33
  }],
  number: 3
}, {
  timelineType: 'comment',
  raw_content: 'woot',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  parent_id: 22,
  created: '28/06/2018 à 15:44:00',
  content_id: 33,
  customClass: ''
}, {
  is_deleted: false,
  is_archived: false,
  sub_content_types: ['thread', 'file', 'folder', 'html-document'],
  raw_content: 'bonjour.\nmerci.',
  status: 'open',
  content_id: 22,
  show_in_ui: true,
  comment_ids: [],
  parent_id: null,
  created: '28/06/2018 à 16:01:41',
  slug: 'current-menu2',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  content_type: 'html-document',
  workspace_id: 1,
  revision_id: 35,
  label: 'Current Menu2',
  timelineType: 'revision',
  commentList: [],
  number: 4
}, {
  is_deleted: false,
  is_archived: false,
  sub_content_types: ['thread', 'file', 'folder', 'html-document'],
  raw_content: 'bonjour.\nmerci.',
  status: 'open',
  content_id: 22,
  show_in_ui: true,
  comment_ids: [],
  parent_id: null,
  created: '28/06/2018 à 16:06:53',
  slug: 'current-menu25',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  content_type: 'html-document',
  workspace_id: 1,
  revision_id: 36,
  label: 'Current Menu25',
  timelineType: 'revision',
  commentList: [],
  number: 5
}, {
  is_deleted: false,
  is_archived: false,
  sub_content_types: ['thread', 'file', 'folder', 'html-document'],
  raw_content: 'bonjour.\nmerci.',
  status: 'open',
  content_id: 22,
  show_in_ui: true,
  comment_ids: [],
  parent_id: null,
  created: '28/06/2018 à 16:23:30',
  slug: '',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  content_type: 'html-document',
  workspace_id: 1,
  revision_id: 37,
  label: '',
  timelineType: 'revision',
  commentList: [],
  number: 6
}, {
  is_deleted: false,
  is_archived: false,
  sub_content_types: ['thread', 'file', 'folder', 'html-document'],
  raw_content: 'bonjour.\nmerci.',
  status: 'open',
  content_id: 22,
  show_in_ui: true,
  comment_ids: [],
  parent_id: null,
  created: '28/06/2018 à 16:23:43',
  slug: 'woot',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  content_type: 'html-document',
  workspace_id: 1,
  revision_id: 38,
  label: 'woot',
  timelineType: 'revision',
  commentList: [],
  number: 7
}, {
  is_deleted: false,
  is_archived: false,
  sub_content_types: ['thread', 'file', 'folder', 'html-document'],
  raw_content: 'bonjour.\nmerci.',
  status: 'open',
  content_id: 22,
  show_in_ui: true,
  comment_ids: [],
  parent_id: null,
  created: '28/06/2018 à 16:35:18',
  slug: 'woot2',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  content_type: 'html-document',
  workspace_id: 1,
  revision_id: 39,
  label: 'woot2',
  timelineType: 'revision',
  commentList: [],
  number: 8
}, {
  is_deleted: false,
  is_archived: false,
  sub_content_types: ['thread', 'file', 'folder', 'html-document'],
  raw_content: 'bonjour.\nmerci.',
  status: 'open',
  content_id: 22,
  show_in_ui: true,
  comment_ids: [],
  parent_id: null,
  created: '28/06/2018 à 16:36:10',
  slug: 'woot3',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  content_type: 'html-document',
  workspace_id: 1,
  revision_id: 40,
  label: 'woot3',
  timelineType: 'revision',
  commentList: [],
  number: 9
}, {
  is_deleted: false,
  is_archived: false,
  sub_content_types: ['thread', 'file', 'folder', 'html-document'],
  raw_content: 'bonjour.\nmerci.',
  status: 'open',
  content_id: 22,
  show_in_ui: true,
  comment_ids: [],
  parent_id: null,
  created: '28/06/2018 à 16:37:21',
  slug: 'woot4',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  content_type: 'html-document',
  workspace_id: 1,
  revision_id: 41,
  label: 'woot4',
  timelineType: 'revision',
  commentList: [],
  number: 10
}, {
  is_deleted: false,
  is_archived: false,
  sub_content_types: ['thread', 'file', 'folder', 'html-document'],
  raw_content: 'bonjour.\nmerci.\nbravo.',
  status: 'open',
  content_id: 22,
  show_in_ui: true,
  comment_ids: [],
  parent_id: null,
  created: '28/06/2018 à 16:37:36',
  slug: 'woot4',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  content_type: 'html-document',
  workspace_id: 1,
  revision_id: 42,
  label: 'woot4',
  timelineType: 'revision',
  commentList: [],
  number: 11
}, {
  is_deleted: false,
  is_archived: false,
  sub_content_types: ['thread', 'file', 'folder', 'html-document'],
  raw_content: 'bonjour.\nmerci.\nbravo.',
  status: 'closed-validated',
  content_id: 22,
  show_in_ui: true,
  comment_ids: [],
  parent_id: null,
  created: '29/06/2018 à 16:04:02',
  slug: 'woot4',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  content_type: 'html-document',
  workspace_id: 1,
  revision_id: 46,
  label: 'woot4',
  timelineType: 'revision',
  commentList: [],
  number: 12
}, {
  is_deleted: false,
  is_archived: false,
  sub_content_types: ['thread', 'file', 'folder', 'html-document'],
  raw_content: 'bonjour.\nmerci.\nbravo.',
  status: 'closed-deprecated',
  content_id: 22,
  show_in_ui: true,
  comment_ids: [],
  parent_id: null,
  created: '29/06/2018 à 16:05:32',
  slug: 'woot4',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  content_type: 'html-document',
  workspace_id: 1,
  revision_id: 47,
  label: 'woot4',
  timelineType: 'revision',
  commentList: [],
  number: 13
}, {
  is_deleted: false,
  is_archived: false,
  sub_content_types: ['thread', 'file', 'folder', 'html-document'],
  raw_content: 'bonjour.\nmerci.\nbravo.',
  status: 'open',
  content_id: 22,
  show_in_ui: true,
  comment_ids: [],
  parent_id: null,
  created: '29/06/2018 à 16:06:35',
  slug: 'woot4',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  content_type: 'html-document',
  workspace_id: 1,
  revision_id: 48,
  label: 'woot4',
  timelineType: 'revision',
  commentList: [],
  number: 14
}, {
  is_deleted: false,
  is_archived: false,
  sub_content_types: ['thread', 'file', 'folder', 'html-document'],
  raw_content: 'bonjour.\nmerci.\nbravo.',
  status: 'closed-deprecated',
  content_id: 22,
  show_in_ui: true,
  comment_ids: [],
  parent_id: null,
  created: '29/06/2018 à 16:08:36',
  slug: 'woot4',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  content_type: 'html-document',
  workspace_id: 1,
  revision_id: 49,
  label: 'woot4',
  timelineType: 'revision',
  commentList: [],
  number: 15
}, {
  is_deleted: false,
  is_archived: false,
  sub_content_types: ['thread', 'file', 'folder', 'html-document'],
  raw_content: 'bonjour.\nmerci.\nbravo.',
  status: 'open',
  content_id: 22,
  show_in_ui: true,
  comment_ids: [],
  parent_id: null,
  created: '29/06/2018 à 16:13:15',
  slug: 'woot4',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  content_type: 'html-document',
  workspace_id: 1,
  revision_id: 50,
  label: 'woot4',
  timelineType: 'revision',
  commentList: [],
  number: 16
}, {
  is_deleted: false,
  is_archived: false,
  sub_content_types: ['thread', 'file', 'folder', 'html-document'],
  raw_content: 'bonjour.\nmerci.\nbravo.',
  status: 'closed-validated',
  content_id: 22,
  show_in_ui: true,
  comment_ids: [],
  parent_id: null,
  created: '29/06/2018 à 16:13:19',
  slug: 'woot4',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  content_type: 'html-document',
  workspace_id: 1,
  revision_id: 51,
  label: 'woot4',
  timelineType: 'revision',
  commentList: [],
  number: 17
}, {
  is_deleted: false,
  is_archived: false,
  sub_content_types: ['thread', 'file', 'folder', 'html-document'],
  raw_content: 'bonjour.\nmerci.\nbravo.',
  status: 'open',
  content_id: 22,
  show_in_ui: true,
  comment_ids: [],
  parent_id: null,
  created: '29/06/2018 à 16:14:34',
  slug: 'woot4',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  content_type: 'html-document',
  workspace_id: 1,
  revision_id: 52,
  label: 'woot4',
  timelineType: 'revision',
  commentList: [],
  number: 18
}, {
  is_deleted: false,
  is_archived: false,
  sub_content_types: ['thread', 'file', 'folder', 'html-document'],
  raw_content: 'bonjour.\nmerci.\nbravo.',
  status: 'closed-unvalidated',
  content_id: 22,
  show_in_ui: true,
  comment_ids: [],
  parent_id: null,
  created: '29/06/2018 à 16:14:38',
  slug: 'woot4',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  content_type: 'html-document',
  workspace_id: 1,
  revision_id: 53,
  label: 'woot4',
  timelineType: 'revision',
  commentList: [],
  number: 19
}, {
  is_deleted: false,
  is_archived: false,
  sub_content_types: ['thread', 'file', 'folder', 'html-document'],
  raw_content: 'bonjour.\nmerci.\nbravo.',
  status: 'closed-deprecated',
  content_id: 22,
  show_in_ui: true,
  comment_ids: [],
  parent_id: null,
  created: '29/06/2018 à 16:15:29',
  slug: 'woot4',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  content_type: 'html-document',
  workspace_id: 1,
  revision_id: 54,
  label: 'woot4',
  timelineType: 'revision',
  commentList: [],
  number: 20
}, {
  is_deleted: false,
  is_archived: false,
  sub_content_types: ['thread', 'file', 'folder', 'html-document'],
  raw_content: 'bonjour.\nmerci.\nbravo.',
  status: 'open',
  content_id: 22,
  show_in_ui: true,
  comment_ids: [],
  parent_id: null,
  created: '29/06/2018 à 16:15:43',
  slug: 'woot4',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  content_type: 'html-document',
  workspace_id: 1,
  revision_id: 55,
  label: 'woot4',
  timelineType: 'revision',
  commentList: [],
  number: 21
}, {
  is_deleted: false,
  is_archived: false,
  sub_content_types: ['thread', 'file', 'folder', 'html-document'],
  raw_content: 'bonjour.\nmerci.\nbravo.',
  status: 'closed-unvalidated',
  content_id: 22,
  show_in_ui: true,
  comment_ids: [],
  parent_id: null,
  created: '29/06/2018 à 16:15:53',
  slug: 'woot4',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  content_type: 'html-document',
  workspace_id: 1,
  revision_id: 56,
  label: 'woot4',
  timelineType: 'revision',
  commentList: [],
  number: 22
}, {
  is_deleted: false,
  is_archived: false,
  sub_content_types: ['thread', 'file', 'folder', 'html-document'],
  raw_content: 'bonjour.\nmerci.\nbravo.',
  status: 'closed-deprecated',
  content_id: 22,
  show_in_ui: true,
  comment_ids: [],
  parent_id: null,
  created: '29/06/2018 à 16:15:55',
  slug: 'woot4',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  content_type: 'html-document',
  workspace_id: 1,
  revision_id: 57,
  label: 'woot4',
  timelineType: 'revision',
  commentList: [],
  number: 23
}, {
  is_deleted: false,
  is_archived: false,
  sub_content_types: ['thread', 'file', 'folder', 'html-document'],
  raw_content: '<p>bonjour.</p>\n<p>merci.</p>\n<p>bravo.</p>',
  status: 'closed-deprecated',
  content_id: 22,
  show_in_ui: true,
  comment_ids: [36, 37, 38, 39, 40, 41, 42],
  parent_id: null,
  created: '02/07/2018 à 12:46:16',
  slug: 'woot4',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  content_type: 'html-document',
  workspace_id: 1,
  revision_id: 58,
  label: 'woot4',
  timelineType: 'revision',
  commentList: [{
    timelineType: 'comment',
    raw_content: '<p>test<br />1</p>',
    author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
    parent_id: 22,
    created: '02/07/2018 à 12:47:22',
    content_id: 36
  }, {
    timelineType: 'comment',
    raw_content: 'test',
    author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
    parent_id: 22,
    created: '02/07/2018 à 12:50:12',
    content_id: 37
  }, {
    timelineType: 'comment',
    raw_content: '<p>123</p>',
    author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
    parent_id: 22,
    created: '02/07/2018 à 15:14:55',
    content_id: 38
  }, {
    timelineType: 'comment',
    raw_content: '123',
    author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
    parent_id: 22,
    created: '02/07/2018 à 15:19:31',
    content_id: 39
  }, {
    timelineType: 'comment',
    raw_content: '<p>aze</p>',
    author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
    parent_id: 22,
    created: '02/07/2018 à 15:20:54',
    content_id: 40
  }, {
    timelineType: 'comment',
    raw_content: 'aze',
    author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
    parent_id: 22,
    created: '02/07/2018 à 15:33:28',
    content_id: 41
  }, {
    timelineType: 'comment',
    raw_content: 'aze',
    author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
    parent_id: 22,
    created: '02/07/2018 à 15:47:33',
    content_id: 42
  }],
  number: 24
}, {
  timelineType: 'comment',
  raw_content: '<p>test<br />1</p>',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  parent_id: 22,
  created: '02/07/2018 à 12:47:22',
  content_id: 36,
  customClass: ''
}, {
  timelineType: 'comment',
  raw_content: 'test',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  parent_id: 22,
  created: '02/07/2018 à 12:50:12',
  content_id: 37,
  customClass: ''
}, {
  timelineType: 'comment',
  raw_content: '<p>123</p>',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  parent_id: 22,
  created: '02/07/2018 à 15:14:55',
  content_id: 38,
  customClass: ''
}, {
  timelineType: 'comment',
  raw_content: '123',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  parent_id: 22,
  created: '02/07/2018 à 15:19:31',
  content_id: 39,
  customClass: ''
}, {
  timelineType: 'comment',
  raw_content: '<p>aze</p>',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  parent_id: 22,
  created: '02/07/2018 à 15:20:54',
  content_id: 40,
  customClass: ''
}, {
  timelineType: 'comment',
  raw_content: 'aze',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  parent_id: 22,
  created: '02/07/2018 à 15:33:28',
  content_id: 41,
  customClass: ''
}, {
  timelineType: 'comment',
  raw_content: 'aze',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  parent_id: 22,
  created: '02/07/2018 à 15:47:33',
  content_id: 42,
  customClass: ''
}, {
  is_deleted: false,
  is_archived: false,
  sub_content_types: ['thread', 'file', 'folder', 'html-document'],
  raw_content: '<p>bonjour.</p>\n<p>merci.</p>\n<p>bravo.1</p>',
  status: 'closed-deprecated',
  content_id: 22,
  show_in_ui: true,
  comment_ids: [],
  parent_id: null,
  created: '02/07/2018 à 15:48:04',
  slug: 'woot4',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  content_type: 'html-document',
  workspace_id: 1,
  revision_id: 66,
  label: 'woot4',
  timelineType: 'revision',
  commentList: [],
  number: 25
}, {
  is_deleted: false,
  is_archived: false,
  sub_content_types: ['thread', 'file', 'folder', 'html-document'],
  raw_content: '<p>bonjour.</p>\n<p>merci.</p>\n<p>bravo.1</p>',
  status: 'open',
  content_id: 22,
  show_in_ui: true,
  comment_ids: [],
  parent_id: null,
  created: '02/07/2018 à 15:49:32',
  slug: 'woot4',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  content_type: 'html-document',
  workspace_id: 1,
  revision_id: 67,
  label: 'woot4',
  timelineType: 'revision',
  commentList: [],
  number: 26
}, {
  is_deleted: false,
  is_archived: false,
  sub_content_types: ['thread', 'file', 'folder', 'html-document'],
  raw_content: '<p>bonjour.</p>\n<p>merci.</p>\n<p>bravo.12</p>',
  status: 'open',
  content_id: 22,
  show_in_ui: true,
  comment_ids: [],
  parent_id: null,
  created: '02/07/2018 à 15:50:36',
  slug: 'woot4',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  content_type: 'html-document',
  workspace_id: 1,
  revision_id: 68,
  label: 'woot4',
  timelineType: 'revision',
  commentList: [],
  number: 27
}, {
  is_deleted: false,
  is_archived: false,
  sub_content_types: ['thread', 'file', 'folder', 'html-document'],
  raw_content: '<p>bonjour.</p>\n<p>merci.</p>\n<p>bravo.123</p>',
  status: 'open',
  content_id: 22,
  show_in_ui: true,
  comment_ids: [],
  parent_id: null,
  created: '02/07/2018 à 15:54:17',
  slug: 'woot4',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  content_type: 'html-document',
  workspace_id: 1,
  revision_id: 69,
  label: 'woot4',
  timelineType: 'revision',
  commentList: [],
  number: 28
}, {
  is_deleted: false,
  is_archived: false,
  sub_content_types: ['thread', 'file', 'folder', 'html-document'],
  raw_content: '<p>bonjour.</p>\n<p>merci.</p>\n<p>bravo.1234</p>',
  status: 'open',
  content_id: 22,
  show_in_ui: true,
  comment_ids: [],
  parent_id: null,
  created: '02/07/2018 à 15:54:22',
  slug: 'woot4',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  content_type: 'html-document',
  workspace_id: 1,
  revision_id: 70,
  label: 'woot4',
  timelineType: 'revision',
  commentList: [],
  number: 29
}, {
  is_deleted: false,
  is_archived: false,
  sub_content_types: ['thread', 'file', 'folder', 'html-document'],
  raw_content: '<p>end</p>',
  status: 'open',
  content_id: 22,
  show_in_ui: true,
  comment_ids: [],
  parent_id: null,
  created: '02/07/2018 à 17:24:41',
  slug: 'woot4',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  content_type: 'html-document',
  workspace_id: 1,
  revision_id: 71,
  label: 'woot4',
  timelineType: 'revision',
  commentList: [],
  number: 30
}, {
  is_deleted: false,
  is_archived: false,
  sub_content_types: ['thread', 'file', 'folder', 'html-document'],
  raw_content: '<p>bonjour.</p>\n<p>merci.</p>\n<p>bravo.12</p>',
  status: 'open',
  content_id: 22,
  show_in_ui: true,
  comment_ids: [43],
  parent_id: null,
  created: '02/07/2018 à 17:43:28',
  slug: 'woot5',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  content_type: 'html-document',
  workspace_id: 1,
  revision_id: 72,
  label: 'woot5',
  timelineType: 'revision',
  commentList: [{
    timelineType: 'comment',
    raw_content: 'ceci est un commentaire',
    author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
    parent_id: 22,
    created: '04/07/2018 à 11:02:14',
    content_id: 43
  }],
  number: 31
}, {
  timelineType: 'comment',
  raw_content: 'ceci est un commentaire',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  parent_id: 22,
  created: '04/07/2018 à 11:02:14',
  content_id: 43,
  customClass: ''
}, {
  is_deleted: false,
  is_archived: false,
  sub_content_types: ['thread', 'file', 'folder', 'html-document'],
  raw_content: '<p>bonjour.</p>\n<p>merci.</p>\n<p>bravo.12</p>\n<p>&nbsp;</p>',
  status: 'open',
  content_id: 22,
  show_in_ui: true,
  comment_ids: [],
  parent_id: null,
  created: '04/07/2018 à 11:02:27',
  slug: 'woot5',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  content_type: 'html-document',
  workspace_id: 1,
  revision_id: 76,
  label: 'woot5',
  timelineType: 'revision',
  commentList: [],
  number: 32
}, {
  is_deleted: false,
  is_archived: false,
  sub_content_types: ['thread', 'file', 'folder', 'html-document'],
  raw_content: '<p>bonjour.</p>\n<p>merci.</p>\n<p>bravo.12</p>\n<p>gni</p>',
  status: 'open',
  content_id: 22,
  show_in_ui: true,
  comment_ids: [],
  parent_id: null,
  created: '04/07/2018 à 11:03:53',
  slug: 'woot5',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  content_type: 'html-document',
  workspace_id: 1,
  revision_id: 77,
  label: 'woot5',
  timelineType: 'revision',
  commentList: [],
  number: 33
}, {
  is_deleted: false,
  is_archived: false,
  sub_content_types: ['thread', 'file', 'folder', 'html-document'],
  raw_content: '<p>bonjour.</p>\n<p>merci.</p>\n<p>bravo.12</p>\n<p>gni</p>\n<p>avec un commentaire ?</p>',
  status: 'open',
  content_id: 22,
  show_in_ui: true,
  comment_ids: [44],
  parent_id: null,
  created: '04/07/2018 à 11:04:19',
  slug: 'woot5',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  content_type: 'html-document',
  workspace_id: 1,
  revision_id: 78,
  label: 'woot5',
  timelineType: 'revision',
  commentList: [{
    timelineType: 'comment',
    raw_content: 'lach ton com',
    author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
    parent_id: 22,
    created: '04/07/2018 à 11:04:33',
    content_id: 44
  }],
  number: 34
}, {
  timelineType: 'comment',
  raw_content: 'lach ton com',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  parent_id: 22,
  created: '04/07/2018 à 11:04:33',
  content_id: 44,
  customClass: ''
}, {
  is_deleted: false,
  is_archived: false,
  sub_content_types: ['thread', 'file', 'folder', 'html-document'],
  raw_content: '<p>bonjour.</p>\n<p>merci.</p>\n<p>bravo.12</p>\n<p>gni</p>\n<p>avec un commentaire ?</p>\n<p>fail.</p>',
  status: 'open',
  content_id: 22,
  show_in_ui: true,
  comment_ids: [],
  parent_id: null,
  created: '04/07/2018 à 11:04:39',
  slug: 'woot5',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  content_type: 'html-document',
  workspace_id: 1,
  revision_id: 80,
  label: 'woot5',
  timelineType: 'revision',
  commentList: [],
  number: 35
}, {
  is_deleted: false,
  is_archived: false,
  sub_content_types: ['thread', 'file', 'folder', 'html-document'],
  raw_content: '<p>bonjour.</p>\n<p>merci.</p>\n<p>bravo.12</p>\n<p>gni</p>\n<p>avec un commentaire ?</p>\n<p>fail.</p>',
  status: 'closed-validated',
  content_id: 22,
  show_in_ui: true,
  comment_ids: [],
  parent_id: null,
  created: '04/07/2018 à 11:05:13',
  slug: 'woot5',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  content_type: 'html-document',
  workspace_id: 1,
  revision_id: 81,
  label: 'woot5',
  timelineType: 'revision',
  commentList: [],
  number: 36
}, {
  is_deleted: false,
  is_archived: false,
  sub_content_types: ['thread', 'file', 'folder', 'html-document'],
  raw_content: '<p>bonjour.</p>\n<p>merci.</p>\n<p>bravo.12</p>\n<p>gni</p>\n<p>avec un commentaire ?</p>\n<p>fail.</p>',
  status: 'open',
  content_id: 22,
  show_in_ui: true,
  comment_ids: [],
  parent_id: null,
  created: '04/07/2018 à 11:05:19',
  slug: 'woot5',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  content_type: 'html-document',
  workspace_id: 1,
  revision_id: 82,
  label: 'woot5',
  timelineType: 'revision',
  commentList: [],
  number: 37
}, {
  is_deleted: false,
  is_archived: false,
  sub_content_types: ['thread', 'file', 'folder', 'html-document'],
  raw_content: '<p>bonjour.</p>\n<p>merci.</p>\n<p>bravo.12</p>\n<p>gni</p>\n<p>avec un commentaire ?</p>\n<p>fail.</p>',
  status: 'closed-validated',
  content_id: 22,
  show_in_ui: true,
  comment_ids: [],
  parent_id: null,
  created: '04/07/2018 à 13:11:50',
  slug: 'woot5',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  content_type: 'html-document',
  workspace_id: 1,
  revision_id: 83,
  label: 'woot5',
  timelineType: 'revision',
  commentList: [],
  number: 38
}, {
  is_deleted: false,
  is_archived: false,
  sub_content_types: ['thread', 'file', 'folder', 'html-document'],
  raw_content: '<p>bonjour.</p>\n<p>merci.</p>\n<p>bravo.12</p>\n<p>gni</p>\n<p>avec un commentaire ?</p>\n<p>fail.</p>',
  status: 'open',
  content_id: 22,
  show_in_ui: true,
  comment_ids: [45, 59, 60, 61],
  parent_id: null,
  created: '04/07/2018 à 14:26:43',
  slug: 'woot5',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  content_type: 'html-document',
  workspace_id: 1,
  revision_id: 84,
  label: 'woot5',
  timelineType: 'revision',
  commentList: [{
    timelineType: 'comment',
    raw_content: 'test',
    author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
    parent_id: 22,
    created: '04/07/2018 à 16:26:20',
    content_id: 45
  }, {
    timelineType: 'comment',
    raw_content: 'bonjour',
    author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
    parent_id: 22,
    created: '06/07/2018 à 16:12:08',
    content_id: 59
  }, {
    timelineType: 'comment',
    raw_content: 'test',
    author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
    parent_id: 22,
    created: '06/07/2018 à 16:14:37',
    content_id: 60
  }, {
    timelineType: 'comment',
    raw_content: 'gni',
    author: { user_id: 4, avatar_url: null, public_name: 'john' },
    parent_id: 22,
    created: '06/07/2018 à 16:21:43',
    content_id: 61
  }],
  number: 39
}, {
  timelineType: 'comment',
  raw_content: 'test',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  parent_id: 22,
  created: '04/07/2018 à 16:26:20',
  content_id: 45,
  customClass: ''
}, {
  timelineType: 'comment',
  raw_content: 'bonjour',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  parent_id: 22,
  created: '06/07/2018 à 16:12:08',
  content_id: 59,
  customClass: ''
}, {
  timelineType: 'comment',
  raw_content: 'test',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  parent_id: 22,
  created: '06/07/2018 à 16:14:37',
  content_id: 60,
  customClass: ''
}, {
  timelineType: 'comment',
  raw_content: 'gni',
  author: { user_id: 4, avatar_url: null, public_name: 'john' },
  parent_id: 22,
  created: '06/07/2018 à 16:21:43',
  content_id: 61,
  customClass: ''
}, {
  is_deleted: false,
  is_archived: false,
  sub_content_types: ['thread', 'file', 'folder', 'html-document'],
  raw_content: '<p>bonjour.</p>\n<p>merci.</p>\n<p>bravo.12</p>\n<p>gni</p>\n<p>avec un commentaire ?</p>\n<p>fail.</p>',
  status: 'closed-validated',
  content_id: 22,
  show_in_ui: true,
  comment_ids: [64, 65],
  parent_id: null,
  created: '06/07/2018 à 16:21:52',
  slug: 'woot5',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  content_type: 'html-document',
  workspace_id: 1,
  revision_id: 109,
  label: 'woot5',
  timelineType: 'revision',
  commentList: [{
    timelineType: 'comment',
    raw_content: 'je suis john',
    author: { user_id: 4, avatar_url: null, public_name: 'john' },
    parent_id: 22,
    created: '06/07/2018 à 16:40:22',
    content_id: 64
  }, {
    timelineType: 'comment',
    raw_content: 'je suis admin',
    author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
    parent_id: 22,
    created: '06/07/2018 à 16:57:00',
    content_id: 65
  }],
  number: 40
}, {
  timelineType: 'comment',
  raw_content: 'je suis john',
  author: { user_id: 4, avatar_url: null, public_name: 'john' },
  parent_id: 22,
  created: '06/07/2018 à 16:40:22',
  content_id: 64,
  customClass: ''
}, {
  timelineType: 'comment',
  raw_content: 'je suis admin',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  parent_id: 22,
  created: '06/07/2018 à 16:57:00',
  content_id: 65,
  customClass: ''
}, {
  is_deleted: false,
  is_archived: false,
  sub_content_types: ['thread', 'file', 'folder', 'html-document'],
  raw_content: '<p>bonjour.</p>\n<p>merci.</p>\n<p>bravo.12</p>\n<p>gni</p>\n<p>avec un commentaire ?</p>\n<p>fail.</p>',
  status: 'closed-validated',
  content_id: 22,
  show_in_ui: true,
  comment_ids: [],
  parent_id: null,
  created: '06/07/2018 à 18:15:04',
  slug: 'woot55',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  content_type: 'html-document',
  workspace_id: 1,
  revision_id: 115,
  label: 'woot55',
  timelineType: 'revision',
  commentList: [],
  number: 41
}, {
  is_deleted: false,
  is_archived: false,
  sub_content_types: ['thread', 'file', 'folder', 'html-document'],
  raw_content: '<p>bonjour.</p>\n<p>merci.</p>\n<p>bravo.12</p>\n<p>gni</p>\n<p>avec un commentaire ?</p>\n<p>fail.</p>',
  status: 'open',
  content_id: 22,
  show_in_ui: true,
  comment_ids: [],
  parent_id: null,
  created: '06/07/2018 à 18:15:20',
  slug: 'woot55',
  author: { user_id: 1, avatar_url: null, public_name: 'Global manager' },
  content_type: 'html-document',
  workspace_id: 1,
  revision_id: 116,
  label: 'woot55',
  timelineType: 'revision',
  commentList: [],
  number: 42
}]

export default TimelineDebugData
