#!/bin/sh
# NOTE 2021-09-29 - SG - sh here as the used docker image doesn't include bash.
set -e

ATC_EXTERNAL_URL=$(cat atc_external_url)
BUILD_PIPELINE_NAME=$(cat build_pipeline_name)
BUILD_TEAM_NAME=$(cat build_team_name)
BUILD_ID=$(cat build_id)
FLY=/usr/bin/fly

if [ ! -f $FLY ]; then
  wget -q -O "$FLY" "$ATC_EXTERNAL_URL/api/v1/cli?arch=amd64&platform=linux"
  chmod +x $FLY
fi

echo "Pipeline: $BUILD_PIPELINE_NAME, instance vars: $BUILD_PIPELINE_INSTANCE_VARS"
$FLY login -t algoo -c "$ATC_EXTERNAL_URL" -n "$BUILD_TEAM_NAME" -u "$CONCOURSE_USER" -p "$CONCOURSE_PASSWORD"
build_ids=$("$FLY" -t algoo builds -p "$BUILD_PIPELINE_NAME" --json | jq '.[] | select(.status=="started" or .status=="pending") | .id')

echo "Found following builds to abort: [$build_ids]"
for id in $build_ids; do
  # Let's not abort ourselves!!
  if [ "$id" != "$BUILD_ID" ]; then
    $FLY -t algoo abort-build -b "$id";
  fi;
done
