#!/bin/bash
set -e

script_dir="$(realpath $(dirname $0))"
source "$script_dir/util-lib.sh"
skip_if_no_changed_file_match "^(backend|concourse)"

source "$HOME/.bashrc"
pyenv shell "$PYTHON_VERSION"

cd backend
pip install -r requirements-devtool.txt
flake8 --version
isort --version
black --version
flake8
