#!/bin/bash
set -e

source $(dirname $0)/install_docker
source $(dirname $0)/install_backend_packages
source $(dirname $0)/create_backend_dirs
cd backend
pip install -r requirements.txt -r requirements-test.txt
python setup.py develop
# Prepare docker to run in another docker
source "$(dirname 0)/docker-lib.sh"
start_docker
docker-compose up -d redis
pytest --ignore "tracim_backend/tests/functional" --ignore "tracim_backend/tests/commands"
