#!/bin/bash
set -e

"$(dirname $0)"/install_docker
"$(dirname $0)"/install_backend_packages
"$(dirname $0)"/create_backend_dirs backend/test_storage_dir
cd backend
pip install -r requirements.txt -r requirements-test.txt
python setup.py develop
docker-compose up -d redis
pytest --ignore "tracim_backend/tests/functional" --ignore "tracim_backend/tests/commands"
