#!/bin/bash
set -e

script_dir="$(realpath $(dirname $0))"
source "$script_dir/util-lib.sh"
skip_if_no_changed_file_match "backend"


source "$HOME/.bashrc"
python_version=${1:-3.6.14}
pyenv shell "$python_version"

cd backend
pip install -r requirements-devtool.txt
flake8 --version
flake8
