#!/bin/bash
set -e

"$(dirname $0)"/install_docker
"$(dirname $0)"/install_backend_packages
"$(dirname $0)"/create_backend_dirs backend
cd backend
pip install -r requirements.txt
python setup.py develop
# Update pyenv shims so that tracimcli is found
pyenv rehash
cp development.ini.sample development.ini
tracimcli db init -d
cd -
./setup_functionnal_tests.sh root
./install_frontend_dependencies.sh
./build_full_frontend.sh
# Prepare docker to run in another docker
source "$(dirname $0)/docker-lib.sh"
start_docker
./run_dev_backend.sh cypress run
