#!/bin/bash
set -e

command -v pyenv || (echo "need pyenv installed" && exit 1)
# TODO: this shouldn't be necessary here…
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
cd backend
for version in $@; do
  pyenv install "$version"
  pyenv shell "$version"
  pip install -r requirements-build.txt
  pip install -r requirements.txt
  pip install -r requirements-test.txt
  pip install -r requirements-storage-s3.txt
  pip install $(for r in requirements-db*.txt; do echo "-r $r"; done)
done
