#!/bin/bash
set -e

python_version=$1
shift
# FIXME: find a way to include pyenv in the PATH during image build !!!
export PATH=/root/.pyenv/bin/:$PATH
eval "$(pyenv init -)"
pyenv shell "$python_version"
python --version
echo "PIP: $(which pip) PIP3: $(which pip3)"
"$@"
