#!/bin/bash
set -e

python_version=$1
shift
# FIXME: find a way to include pyenv in the PATH during image build !!!
export PATH=/root/.pyenv/shims:/root/.pyenv/bin/:$PATH
eval "$(pyenv init -)"
pyenv shell "$python_version"
echo "Running $@ using python version $(python --version)"
$@
