#!/bin/bash
set -e

python_version=$1
shift
# FIXME: find a way to include pyenv in the PATH during image build !!!
export PATH=/root/.pyenv/shims:/root/.pyenv/bin/:$PATH
eval "$(pyenv init -)"
pyenv shell "$python_version"

# Prepare docker to run in another docker
source "$(dirname $0)/docker-lib.sh"
# TODO - S.G. - 2021-08-04 - parametrize the registry mirror
start_docker "" "172.17.0.1:5000"
echo "Running $@ using $(python --version)"
$@
