<!DOCTYPE html>
<html lang="${lang}">
<body>
    <%
        # FIXME - G.M - 2019-05-09 - After discuss with Damien: dont add intelligent code in template,
        # see issue #1691
        call_to_action_url = content_in_context.frontend_url
        content_name_pattern = "<i><a href={call_to_action_url}>{content}</a></i>"
        content_name = content_name_pattern.format(
                    call_to_action_url=html_escape(call_to_action_url),
                    content=html_escape(content_in_context.label)
         )
        if action == ActionDescription.COMMENT:
          call_to_action_url = parent_in_context.frontend_url
    %>
<style>
  ins { background-color: #c0ffc0; }
  del { background-color: #ffc0c0; }
</style>

<%block>
    %if action == ActionDescription.COMMENT:
        <%
            call_to_action_url = parent_in_context.frontend_url
        %>
        <div>
            ${content_in_context.raw_content| n}
        </div>
    %elif action == ActionDescription.STATUS_UPDATE:
        <p>
            ${_( "I modified the status of {content_name}. The new status is <i>{new_status}</i>" ).format(content_name=content_name, new_status=html_escape(new_status))| n}
        </p>
    %elif action == ActionDescription.CREATION:
        <p>
            ${_("I added an item entitled {content_name}.").format(
                content_name=content_name
            )| n }
        </p>
    %elif action in (ActionDescription.REVISION, ActionDescription.EDITION):
        <p>
            ${_("I updated {content_name}.").format(content_name=content_name)|n}
        </p>
        <%
            title_diff = htmldiff(html_escape(previous_revision.label), html_escape(content_in_context.label))
            content_diff = htmldiff(previous_revision.raw_content, content_in_context.raw_content)
        %>
        %if title_diff or content_diff:
            <p>${_("Here is an overview of the changes:")}</p>
            <br/>
            <div style="border-left: 1em solid #ccc; padding-left: 0.5em;">
                <br/>
                <b>${title_diff| n}</b>
                ${content_diff| n}
            </div>
        %endif
    %endif
</%block>

<p style="font-size: 0.8em; color: #5e5c64">
  --<br/>
  % if config.EMAIL__REPLY__ACTIVATED:
      ${_('Reply to this email directly or <a href="{call_to_action_url}">view it on tracim</a>').format(call_to_action_url=html_escape(call_to_action_url))|n}
  % else:
      ${_('<a href="{call_to_action_url}">view it on tracim</a>').format(call_to_action_url=html_escape(call_to_action_url))|n}
  %endif
  <br/>
  ${_("You are receiving this email because you have an account on {website_title}.").format(website_title=config.WEBSITE__TITLE)}<br />
  ${_('You can change this setting by going to the "My Spaces" menu through this link:')}
  <a href="${config.WEBSITE__BASE_URL}/ui/account">${config.WEBSITE__BASE_URL}/ui/account</a>.<br/>
  ${_("This e-mail was automatically generated by the")} <a href="https://www.tracim.fr">Tracim software</a> ${_("that powers {website_title}, please do not reply.").format(website_title=config.WEBSITE__TITLE)}
</p>
</body>
</html>
