<!DOCTYPE html>
<html lang="${lang}">
<body>
<p>${_('Hello {username},').format(username=user.display_name)}</p>

<p>${_('Someone has requested to reset the password for your account on <i>{website_title}</i>.').format(website_title=html_escape(config.WEBSITE__TITLE))| n}</p>

<p>${_('If you did not perform this request, you can safely ignore this email.')}</p>

<p>
  ${_('In order to reset your password, please click on following link :')}
  <a href="${reset_password_url}" id='call-to-action-button'>${_('Reset my password')}</a>
  <br/>
  <i>${_('If the link is not working, I suggest to copy/paste the full url: ')}</i>
</p>
<pre>${reset_password_url}</pre>

## the lifetime is converted from seconds to minutes.
${_('The link is valid for {} minutes.'.format(config.USER__RESET_PASSWORD__TOKEN_LIFETIME // 60))}

<p style="font-size: 0.8em; color: #5e5c64">
  --<br/>
  ${_("You are receiving this email because you have an account on {website_title}.").format(website_title=config.WEBSITE__TITLE)}<br />
  ${_('You can change this setting by going to the "My Spaces" menu through this link:')}
  <a href="${config.WEBSITE__BASE_URL}/ui/account">${config.WEBSITE__BASE_URL}/ui/account</a>.<br/>
  ${_("This e-mail was automatically generated by the")} <a href="https://www.tracim.fr">Tracim software</a> ${_("that powers {website_title}, please do not reply.").format(website_title=config.WEBSITE__TITLE)}
</p>
</body>
</html>
