<!DOCTYPE html>
<html lang="${lang}">
<body>
%if receiver.username:
    <p>${_('Hello {username},').format(username=receiver.username)}</p>
%else:
    <p>${_('Hello,')}</p>
%endif
<p>${_('I share a file with you, download it here:')}</p>

<p>${_('<a href="{url}" id="call-to-action-button">{filename}</a> ({file_size})').format(
   url=html_escape(content_share.url),
   filename=html_escape(shared_content.filename),
   file_size=html_escape(humanize.naturalsize(shared_content.size))
)|n}</p>

%if share_password_enabled:
    <p>${_('This file is protected by a password, please contact me (<a href="mailto:{emitter_email}">{username}</a>) to get the password.').format(emitter_email=html_escape(emitter.email),username=html_escape(emitter.display_name))|n}</p>
    <p>${_("Note: You can also use this link: {url}").format(url=content_share.url)}<p>
%else:
    <p>${_("Note: You can also use this direct link: {direct_url}").format(direct_url=content_share.direct_url)}<p>
%endif

<p>${_("Thanks a lot")}</p>
<p>${_("{username} (through tracim)").format(username=emitter.display_name)}</p>


<p style="font-size: 0.8em; color: #5e5c64">
  --<br/>
  ${_("You are receiving this email because you have an account on {website_title}.").format(website_title=config.WEBSITE__TITLE)}<br />
  ${_('You can change this setting by going to the "My Spaces" menu through this link:')}
  <a href="${config.WEBSITE__BASE_URL}/ui/account">${config.WEBSITE__BASE_URL}/ui/account</a>.<br/>
  ${_("This e-mail was automatically generated by the")} <a href="https://www.tracim.fr">Tracim software</a> ${_("that powers {website_title}, please do not reply.").format(website_title=config.WEBSITE__TITLE)}
</p>
</body>
</html>
