<!DOCTYPE html>
<html lang="${lang}">
<body>
<p>${_('Hello {username},').format(username=emitter.display_name)}</p>
<p>${_('You shared the file <i>{content_filename}</i> with:').format(content_filename=html_escape(shared_content.filename))|n}</p>
<ul>
% for content_share in content_share_receivers:
    <li>${_('<i><a href="{email_link}">{email}</a></i> at this link: <a href="{url}">{url}</a>').format(email=html_escape(content_share.email_user.email_address), email_link=html_escape(content_share.email_user.email_link), url=html_escape(content_share.url))| n}</li>
% endfor
</ul>

%if share_password:
    <p>${_('This file is protected by this password: "{share_password}"').format(share_password=share_password)}</p>
%endif

<p>${_("Enjoy your day :)")}</p>

<p style="font-size: 0.8em; color: #5e5c64">
  --<br/>
  ${_("You are receiving this email because you have an account on {website_title}.").format(website_title=config.WEBSITE__TITLE)}<br />
  ${_('You can change this setting by going to the "My Spaces" menu through this link:')}
  <a href="${config.WEBSITE__BASE_URL}/ui/account">${config.WEBSITE__BASE_URL}/ui/account</a>.<br/>
  ${_("This e-mail was automatically generated by the")} <a href="https://www.tracim.fr">Tracim software</a> ${_("that powers {website_title}, please do not reply.").format(website_title=config.WEBSITE__TITLE)}
</p>
</body>
</html>
