<!DOCTYPE html>
<html lang="${lang}">
<body>
%if receiver.username:
    <p>${_('Hello {username},').format(username=receiver.username)}</p>
%else:
    <p>${_('Hello,')}</p>
%endif
<p>${_( 'I invited you to upload files here:')|n}</p>
<a href="${upload_permission.url}" id='call-to-action-button'>${_('Upload files')}</a>

%if upload_permission_password_enabled:
    <p>${_('This upload is protected by a password, please contact me (<a href="mailto:{emitter_email}">{username}</a>) to get the password.').format(emitter_email=html_escape(emitter.email),username=html_escape(emitter.display_name))|n}</p>
%endif

<p>${_("Note: You can also use this link: {url}").format(url=upload_permission.url)}<p>

<p>${_("Thanks a lot")}</p>
<p>${_("{username} (through tracim)").format(username=emitter.display_name)}</p>

<p style="font-size: 0.8em; color: #5e5c64">
  --<br/>
  ${_("You are receiving this email because you have an account on {website_title}.").format(website_title=config.WEBSITE__TITLE)}<br />
  ${_('You can change this setting by going to the "My Spaces" menu through this link:')}
  <a href="${config.WEBSITE__BASE_URL}/ui/account">${config.WEBSITE__BASE_URL}/ui/account</a>.<br/>
  ${_("This e-mail was automatically generated by the")} <a href="https://www.tracim.fr">Tracim software</a> ${_("that powers {website_title}, please do not reply.").format(website_title=config.WEBSITE__TITLE)}
</p>
</body>
</html>
