<!DOCTYPE html>
<html lang="${lang}">
<body>
<p>${_('Hello {username},').format(username=emitter.display_name)}</p>
<p>${_('You have invited {nb_receivers} people to upload files in this space <a href={sharedspace_url}>{sharedspace_name}</a>:').format(sharedspace_name=html_escape(workspace.label), sharedspace_url=html_escape(workspace.frontend_url), nb_receivers=html_escape(len(upload_permission_receivers)))|n}</p>
<ul>
% for upload_permission in upload_permission_receivers:
<li>${_('<i><a href="{email_link}">{email}</a></i> at this link: <a href="{url}">{url}</a>').format(email=html_escape(upload_permission.email_user.email_address), email_link=html_escape(upload_permission.email_user.email_link), url=html_escape(upload_permission.url))| n}</li>
% endfor
</ul>

%if upload_permission_password:
    <p>${_('This upload is protected by this password: "{upload_permission_password}"').format(upload_permission_password=upload_permission_password)}</p>
%endif

<p>${_("Enjoy your day :)")}</p>

<p style="font-size: 0.8em; color: #5e5c64">
  --<br/>
  ${_("You are receiving this email because you have an account on {website_title}.").format(website_title=config.WEBSITE__TITLE)}<br />
  ${_('You can change this setting by going to the "My Spaces" menu through this link:')}
  <a href="${config.WEBSITE__BASE_URL}/ui/account">${config.WEBSITE__BASE_URL}/ui/account</a>.<br/>
  ${_("This e-mail was automatically generated by the")} <a href="https://www.tracim.fr">Tracim software</a> ${_("that powers {website_title}, please do not reply.").format(website_title=config.WEBSITE__TITLE)}
</p>
</body>
</html>
