describe('navigate :: create_new > workspace', function () {
  before(() => {
    cy.resetDB()
    cy.setupBaseDB()
  })

  beforeEach(function () {
    cy.loginAs('administrators')
    cy.visit('/ui/workspaces/1/dashboard')
  })
  it('', function () {
    cy.get('button.sidebar__content__btnnewworkspace__btn.btn').should('be.visible')
    cy.get('button.sidebar__content__btnnewworkspace__btn.btn').click()
    cy.get('.cardPopup__container .newSpace__title').should('be.visible')
    cy.get('.cardPopup__container .newSpace__button .btn').should('be.visible')
    cy.get('.cardPopup__container .newSpace__button .btn').should('be.disabled')
    cy.get('.cardPopup__container .newSpace__input').should('have.attr', 'placeholder')
    cy.get('.cardPopup__container .newSpace__input').type('Space name')
    cy.get('.cardPopup__container .newSpace__input').should('have.attr', 'value', 'Space name')
    cy.get('.cardPopup__container .newSpace__button .btn').should('be.visible')
    cy.get('.cardPopup__container .newSpace__button .btn').should('be.disabled')
    cy.get('.cardPopup__container .singleChoiceList').should('be.visible')
    cy.get('.cardPopup__container .singleChoiceList__item').should('have.length', 3)
    cy.get('.cardPopup__container .singleChoiceList__item').last().click()
    cy.get('.cardPopup__container .newSpace__button .btn').should('be.visible')
    cy.get('.cardPopup__container .newSpace__button .btn').should('not.be.disabled')
    cy.get('.cardPopup__container .newSpace__button .btn').click()
    cy.get('div.newSpace__input').should('be.visible')
    cy.get('.newSpace__button .btn').last().should('be.visible')
    cy.get('.newSpace__button .btn').last().should('be.disabled')
    cy.get('.cardPopup__container .singleChoiceList').should('be.visible')
    cy.get('.cardPopup__container .singleChoiceList__item').should('have.length', 4)
    cy.get('.cardPopup__container .singleChoiceList__item').last().click()
    cy.get('.newSpace__button .btn').last().should('be.visible')
    cy.get('.newSpace__button .btn').last().should('not.be.disabled')
    cy.get('.newSpace__button .btn').first().should('be.visible')
    cy.get('.newSpace__button .btn').first().click()
    cy.get('.cardPopup__container .newSpace__input').should('be.visible')
    cy.get('.cardPopup__container .newSpace__input').should('have.attr', 'value', 'Space name')
    cy.get('.cardPopup__container .cardPopup__close').should('be.visible')
    cy.get('.cardPopup__container .cardPopup__close').click()
    cy.get('.cardPopup__container .newSpace__title').should('not.be.visible')
  })
})
