---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks.git
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
            args: [--markdown-linebreak-ext=md]
            exclude: ^frontend/dist/assets/.*$
          - id: end-of-file-fixer
            exclude: ^frontend/dist/assets/.*$
          - id: check-json
          - id: check-yaml
          - id: debug-statements
          - id: check-merge-conflict
    # backend-specific
    # INFO - PGO - 2026-08-06 - https://algoo.tracim.fr/ui/workspaces/49/contents/html-document/192530
    - repo: https://github.com/psf/black
      rev: 24.10.0
      hooks:
          - id: black
            files: 'backend'
    - repo: https://github.com/PyCQA/isort
      rev: 6.0.0
      hooks:
          - id: isort
            files: 'backend'
    - repo: https://github.com/pycqa/flake8
      rev: 6.1.0
      hooks:
          - id: flake8
            entry: bash -c "cd backend"
            files: 'backend'
