export const CUSTOM_EVENT = {
  ADD_FLASH_MSG: 'addFlashMsg',
  ALL_APP_CHANGE_LANG: 'allApp_changeLang',
  APPEND_BREADCRUMBS: 'appendBreadcrumbs',
  APP_CLOSED: 'appClosed',
  APP_CUSTOM_EVENT: 'appCustomEvent',
  DISCONNECTED_FROM_API: 'disconnectedFromApi',
  HIDE_APP: function(type) { return `${type}_hideApp`; },
  HIDE_POPUP_CREATE_CONTENT: 'hide_popupCreateContent',
  HIDE_POPUP_CREATE_WORKSPACE: 'hide_popupCreateWorkspace',
  OPEN_CONTENT_URL: 'openContentUrl',
  REDIRECT: 'redirect',
  REFRESH_CONTENT_LIST: 'refreshContentList',
  REFRESH_DASHBOARD_MEMBER_LIST: 'refreshDashboardMemberList',
  REFRESH_WORKSPACE_DETAIL: 'refreshWorkspaceDetail',
  REFRESH_WORKSPACE_LIST: 'refreshWorkspaceList',
  REFRESH_WORKSPACE_LIST_THEN_REDIRECT: 'refreshWorkspaceList_then_redirect',
  RELOAD_CONTENT: function(type) { return `${type}_reloadContent`; },
  SET_BREADCRUMBS: 'setBreadcrumbs',
  SHOW_APP: function(type) { return `${type}_showApp`; },
  SHOW_CREATE_WORKSPACE_POPUP: 'showCreateWorkspacePopup',
  TINYMCE_LOADED: 'tinymceLoaded',
  UNMOUNT_APP: 'unmount_app',
}
