SWAGGER_TAG__TRASH_AND_RESTORE_SECTION = "Trash & Restore"
SWAGGER_TAG__ARCHIVE_AND_RESTORE_SECTION = "Archive & Restore"
SWAGGER_TAG__ENABLE_AND_DISABLE_SECTION = "Enable & Disable"
SWAGGER_TAG__NOTIFICATION_SECTION = "Notifications"
SWAGGER_TAG_EVENT_ENDPOINTS = "Event & Messages"
SWAGGER_TAG_USER_CONFIG_ENDPOINTS = "User Configuration"
SWAGGER_TAG_USER_SUBSCRIPTIONS_SECTION = "Subscriptions"
SWAGGER_TAG__ALL_SECTION = "All"


SWAGGER_TAG__CONTENT_ENDPOINTS = "Contents"
SWAGGER_TAG__AUTHENTICATION_ENDPOINTS = "Authentication"
