name: Documentation request
description: Raise an issue related to content.
title: "📝 Doc: "
labels: ["documentation", "to sort"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for wanting to improve Tracim!
        Before you submit, please make sure the documentation change hasn't already been suggested by searching [open](https://github.com/tracim/tracim/issues) and [closed](https://github.com/tracim/tracim/issues?q=is%3Aissue+is%3Aclosed).
  - type: input
    id: contents
    attributes:
      label: What content on Tracim is affected?
      placeholder: Tracim README.md, tracim_frontend_lib BUILD.md, etc...
    validations:
      required: true
  - type: textarea
    id: why-changes
    attributes:
      label: What part(s) of the content would you like to see updated?
      description: |
        - Why should the docs be changed? What use cases does it support?
    validations:
      required: true
  - type: textarea
    id: related-pr
    attributes:
      label: Related PR
      description: |
        Let us know if this is related to an open pull request.
        Leave empty if there is no related PR.
      placeholder: PR #0000
    validations:
      required: false
