COLLABORA_DOCUMENT_EDITION_SLUG = "collabora"
SWAGGER_TAG__COLLABORATIVE_DOCUMENT_EDITION_ENDPOINTS = "Collaborative Document Edition"
COLLABORATIVE_DOCUMENT_EDITION_BASE = "collaborative-document-edition"
