"""add publication_enabled column in workspaces

Revision ID: 1f36b2979f89
Revises: 208eda5a6a80
Create Date: 2021-04-15 11:01:26.641374

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "1f36b2979f89"
down_revision = "208eda5a6a80"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workspaces",
        sa.Column("publication_enabled", sa.Boolean(), server_default=sa.text("1"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspaces", "publication_enabled")
    # ### end Alembic commands ###
