"""add contraint to content table

Revision ID: 39ea2d5317db
Revises: 6152079836c7
Create Date: 2019-02-11 18:14:36.566077

"""

# revision identifiers, used by Alembic.
revision = '39ea2d5317db'
down_revision = '6152079836c7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content') as batch_op:
        # INFO - G.M - 2019-02-11 - set column_value as not nullable
        batch_op.alter_column('file_extension',
                   existing_type=sa.VARCHAR(length=255),
                   nullable=False,
                   existing_server_default=sa.text("''"))
        batch_op.alter_column('label',
                   existing_type=sa.VARCHAR(length=1024),
                   nullable=False)
        batch_op.create_unique_constraint('uq__content__workspace_id', ['workspace_id', 'parent_id', 'label', 'file_extension'])
        batch_op.create_foreign_key('fk_content_parent_id_content', 'content', ['parent_id'], ['id'])
        batch_op.create_foreign_key('fk_content_workspace_id_workspaces', 'workspaces', ['workspace_id'], ['workspace_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content') as batch_op:
        batch_op.drop_constraint('fk_content_workspace_id_workspaces', type_='foreignkey')
        batch_op.drop_constraint('fk_content_parent_id_content', type_='foreignkey')
        batch_op.drop_constraint('uq__content__workspace_id', type_='unique')
        batch_op.alter_column('label',
                   existing_type=sa.VARCHAR(length=1024),
                   nullable=True)
        batch_op.alter_column('file_extension',
                   existing_type=sa.VARCHAR(length=255),
                   nullable=True,
                   existing_server_default=sa.text("''"))
    # ### end Alembic commands ###
