"""Added events and messages tables

Revision ID: 3c92f57c52b2
Revises: 96e812178cec
Create Date: 2020-05-14 09:08:10.278702

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "3c92f57c52b2"
down_revision = "96e812178cec"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("event_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "operation",
            sa.Enum("CREATED", "MODIFIED", "DELETED", name="operationtype"),
            nullable=False,
        ),
        sa.Column(
            "entity_type",
            sa.Enum("USER", "WORKSPACE", "WORKSPACE_USER_ROLE", "CONTENT", name="entitytype"),
            nullable=False,
        ),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("fields", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_events")),
    )
    op.create_table(
        "messages",
        sa.Column("receiver_id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("sent", sa.DateTime(), nullable=True),
        sa.Column("read", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.event_id"], name=op.f("fk_messages_event_id_events")
        ),
        sa.ForeignKeyConstraint(
            ["receiver_id"],
            ["users.user_id"],
            name=op.f("fk_messages_receiver_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("receiver_id", "event_id", name=op.f("pk_messages")),
    )
    op.alter_column("content_revisions", "content_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint(
        "fk_content_revisions_content_id_content", "content_revisions", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_content_revisions_content_id_content"),
        "content_revisions",
        "content",
        ["content_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_content_revisions_content_id_content"), "content_revisions", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_content_revisions_content_id_content",
        "content_revisions",
        "content",
        ["content_id"],
        ["id"],
    )
    op.alter_column("content_revisions", "content_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_table("messages")
    op.drop_table("events")
    # ### end Alembic commands ###
