"""remove permission table

Revision ID: 3de3e7f2b049
Revises: 511ce99e1baa
Create Date: 2020-01-24 16:08:24.040748

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "3de3e7f2b049"
down_revision = "511ce99e1baa"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("group_permission")
    op.drop_table("permissions")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions",
        sa.Column("permission_id", sa.INTEGER(), nullable=False),
        sa.Column("permission_name", sa.VARCHAR(length=63), nullable=False),
        sa.Column("description", sa.VARCHAR(length=255), nullable=True),
        sa.PrimaryKeyConstraint("permission_id", name="pk_permissions"),
        sa.UniqueConstraint("permission_name", name="uq__permissions__permission_name"),
    )
    op.create_table(
        "group_permission",
        sa.Column("group_id", sa.INTEGER(), nullable=False),
        sa.Column("permission_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.group_id"],
            name="fk_group_permission_group_id_groups",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.permission_id"],
            name="fk_group_permission_permission_id_permissions",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("group_id", "permission_id", name="pk_group_permission"),
    )
    # ### end Alembic commands ###
