"""add reaction table

Revision ID: 4d40acd3238c
Revises: 5d54d8602f5a
Create Date: 2021-03-10 10:19:53.941096

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "4d40acd3238c"
down_revision = "5d54d8602f5a"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reaction",
        sa.Column("reaction_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("content_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.Unicode(length=255), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["content.id"],
            name=op.f("fk_reaction_content_id_content"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.user_id"], name=op.f("fk_reaction_owner_id_users")
        ),
        sa.PrimaryKeyConstraint("reaction_id", "content_id", name=op.f("pk_reaction")),
        sa.UniqueConstraint("owner_id", "content_id", "value", name=op.f("uq__reaction__owner_id")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reaction")
    # ### end Alembic commands ###
