"""add_favorite_entity_type

Revision ID: 527a180de9dc
Revises: 239b49c55627
Create Date: 2026-06-18 17:13:27.940814

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "527a180de9dc"
down_revision = "239b49c55627"

enum_name = "entitytype"
old_entity_type_enum_values = (
    "USER",
    "WORKSPACE",
    "WORKSPACE_MEMBER",
    "WORKSPACE_SUBSCRIPTION",
    "CONTENT",
    "MENTION",
    "REACTION",
    "TAG",
    "CONTENT_TAG",
    "USER_CALL",
    "USER_CONFIG",
)
favorite = "FAVORITE"

old_entity_type_enum = sa.Enum(*old_entity_type_enum_values, name=enum_name)
new_entity_type_enum = sa.Enum(*(old_entity_type_enum_values + (favorite,)), name=enum_name)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.replace_enum(
        table_name="events",
        column_name="entity_type",
        from_enum=old_entity_type_enum,
        to_enum=new_entity_type_enum,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.replace_enum(
        table_name="events",
        column_name="entity_type",
        from_enum=new_entity_type_enum,
        to_enum=old_entity_type_enum,
    )
    # ### end Alembic commands ###
