"""add_allowed_space_to_user

Revision ID: 5a4962fb875f
Revises: 3d2017960f01
Create Date: 2019-10-08 15:07:00.940908

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "5a4962fb875f"
down_revision = "3d2017960f01"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users") as batch_op:
        batch_op.add_column(
            sa.Column("allowed_space", sa.Integer(), server_default="0", nullable=False)
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users") as batch_op:
        batch_op.drop_column("allowed_space")
    # ### end Alembic commands ###
