"""add avatar and cover to user

Revision ID: 7c6641d4f934
Revises: 58ae85582ba0
Create Date: 2021-01-19 12:31:13.031546

"""
from alembic import op
import depot
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "7c6641d4f934"
down_revision = "c459890b7103"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users") as batch_op:
        batch_op.add_column(
            sa.Column("avatar", depot.fields.sqlalchemy.UploadedFileField(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("cover", depot.fields.sqlalchemy.UploadedFileField(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("cropped_avatar", depot.fields.sqlalchemy.UploadedFileField(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("cropped_cover", depot.fields.sqlalchemy.UploadedFileField(), nullable=True)
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users") as batch_op:
        batch_op.drop_column("cropped_cover")
        batch_op.drop_column("cropped_avatar")
        batch_op.drop_column("cover")
        batch_op.drop_column("avatar")
    # ### end Alembic commands ###
