"""migration label

Revision ID: 81c3613b0b6e
Revises: 6f36ee7d829e
Create Date: 2022-05-31 10:53:17.379942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81c3613b0b6e'
down_revision = '6f36ee7d829e'

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_revisions', sa.Column('is_template', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_revisions', 'is_template')
    # ### end Alembic commands ###
