"""Add template flag to content revision

Revision ID: 81c3613b0b6e
Revises: 6f36ee7d829e
Create Date: 2022-05-31 10:53:17.379942

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "81c3613b0b6e"
down_revision = "6f36ee7d829e"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("content_revisions") as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_template",
                sa.Boolean(),
                server_default=sa.sql.expression.literal(False),
                nullable=False,
            ),
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("content_revisions") as batch_op:
        batch_op.drop_column("is_template")
    # ### end Alembic commands ###
