"""add external_id to user

Revision ID: 8a9d929b44b9
Revises: f4d030ffd43e
Create Date: 2023-11-08 16:21:10.532016

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "8a9d929b44b9"
down_revision = "f4d030ffd43e"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users") as batch_op:
        batch_op.add_column(
            sa.Column("external_id", sa.VARCHAR(length=255), nullable=False, server_default="a")
        )
        batch_op.create_unique_constraint(op.f("uq__users__external_id"), ["external_id"])
    op.execute("UPDATE users SET external_id = user_id;")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users") as batch_op:
        batch_op.drop_constraint(op.f("uq__users__external_id"), type_="unique")
        batch_op.drop_column("external_id")
    # ### end Alembic commands ###
