"""add external_id to user

Revision ID: 8a9d929b44b9
Revises: f4d030ffd43e
Create Date: 2023-11-08 16:21:10.532016

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "8a9d929b44b9"
down_revision = "f4d030ffd43e"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users") as batch_op:
        batch_op.add_column(
            sa.Column(
                "external_id",
                sa.VARCHAR(length=1024),
                nullable=True,
                unique=True,
            )
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users") as batch_op:
        batch_op.drop_column("external_id")
    # ### end Alembic commands ###
