"""add todo

Revision ID: 8cd1d967d000
Revises: 81c3613b0b6e
Create Date: 2022-06-17 16:30:57.718991

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "8cd1d967d000"
down_revision = "81c3613b0b6e"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "todo",
        sa.Column("todo_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("content_id", sa.Integer(), nullable=False),
        sa.Column("assignee_id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assignee_id"], ["users.user_id"], name=op.f("fk_todo_assignee_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["content.id"],
            name=op.f("fk_todo_content_id_content"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("todo_id", name=op.f("pk_todo")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("todo")
    # ### end Alembic commands ###
