"""add revision_id index to content

Revision ID: 96e812178cec
Revises: 2bb8ccb44ce0
Create Date: 2020-03-31 10:07:54.995550

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "96e812178cec"
down_revision = "2bb8ccb44ce0"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    dialect = op.get_context().dialect
    # INFO G.M - 2020-03-31 - mysql create automatically index on foreign key, do not need to update index
    # and it's very complicated to drop/delete index in a working way to be sure getting the correct index name here.
    if dialect.name != "mysql":
        op.create_index("idx__content__revision_id", "content", ["revision_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    dialect = op.get_context().dialect
    # INFO G.M - 2020-03-31 - mysql create automatically index on foreign key, do not need to update index
    # and it's very complicated to drop/delete index in a working way to be sure getting the correct index name here.
    if dialect.name != "mysql":
        op.drop_index("idx__content__revision_id", table_name="content")
    # ### end Alembic commands ###
