"""migration script for share_group_uuid column

Revision ID: a9f887ad07b9
Revises: 5e43c0f32b48
Create Date: 2019-08-13 14:57:49.163718

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "a9f887ad07b9"
down_revision = "5e43c0f32b48"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("content_shares") as bop:
        bop.alter_column(
            "share_group_id",
            new_column_name="share_group_uuid",
            type_=sa.Unicode(length=255),
            nullable=False,
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("content_shares") as bop:
        bop.alter_column(
            "share_group_uuid",
            new_column_name="share_group_id",
            type_=sa.Unicode(length=255),
            nullable=False,
        )
    # ### end Alembic commands ###
