"""add auth_type enum to user

Revision ID: ab7c7f4bcbc5
Revises: 47b6cb15db5a
Create Date: 2018-11-16 16:30:52.558095

"""

# revision identifiers, used by Alembic.
revision = 'ab7c7f4bcbc5'
down_revision = '47b6cb15db5a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    enum = sa.Enum('INTERNAL', 'LDAP', name='authtype')
    enum.create(op.get_bind(), checkfirst=False)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('auth_type', enum, server_default='INTERNAL', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_column('auth_type')
    sa.Enum(name='authtype').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
