"""add parent_id to workspace table

Revision ID: b8090112ca95
Revises: d67be8359ca7
Create Date: 2020-10-02 12:08:24.844702

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "b8090112ca95"
down_revision = "3f30a1bacf1a"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workspaces") as batch_op:
        batch_op.add_column(sa.Column("parent_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_workspaces_parent_id_workspaces"),
            "workspaces",
            ["parent_id"],
            ["workspace_id"],
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workspaces") as batch_op:
        batch_op.drop_constraint(op.f("fk_workspaces_parent_id_workspaces"), type_="foreignkey")
        batch_op.drop_column("parent_id")
    # ### end Alembic commands ###
