"""fix sequence reaction

Revision ID: bf8c10bf8448
Revises: bf040d1a4922
Create Date: 2021-03-25 14:00:28.756711

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "bf8c10bf8448"
down_revision = "bf040d1a4922"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_context().dialect.name == "postgresql":
        op.execute(
            "ALTER SEQUENCE IF EXISTS reaction_reaction_id_seq RENAME TO seq__reaction__reaction_id ;"
        )
        op.execute("ALTER SEQUENCE IF EXISTS events_event_id_seq RENAME TO seq__events__event_id ;")
        op.execute("ALTER SEQUENCE IF EXISTS content_id_seq RENAME TO seq__content__id ;")
        op.execute(
            "ALTER SEQUENCE IF EXISTS content_revisions_revision_id_seq RENAME TO seq__content_revisions__revision_id ;"
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_context().dialect.name == "postgresql":
        op.execute(
            "ALTER SEQUENCE IF EXISTS seq__reaction__reaction_id RENAME TO reaction_reaction_id_seq;"
        )
        op.execute("ALTER SEQUENCE IF EXISTS seq__events__event_id RENAME TO events_event_id_seq;")
        op.execute("ALTER SEQUENCE IF EXISTS seq__content__id RENAME TO content_id_seq;")
        op.execute(
            "ALTER SEQUENCE IF EXISTS seq__content_revisions__revision_id RENAME TO content_revisions_revision_id_seq ;"
        )
