"""use json for upload file field

Revision ID: bff384e7c14b
Revises: 2d98f4b6596d
Create Date: 2021-03-11 14:33:13.584108

"""
# revision identifiers, used by Alembic.
from alembic import op
from sqlalchemy import JSON
from sqlalchemy import VARCHAR

revision = "bff384e7c14b"
down_revision = "2d98f4b6596d"

REDUCED_SIZE_FOR_DEPOT_STORAGE_JSON = 3000


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("users") as batch_op:
        batch_op.alter_column("avatar", type_=JSON, postgresql_using="avatar::json")
        batch_op.alter_column("cropped_avatar", type_=JSON, postgresql_using="cropped_avatar::json")
        batch_op.alter_column("cover", type_=JSON, postgresql_using="cover::json")
        batch_op.alter_column("cropped_cover", type_=JSON, postgresql_using="cropped_cover::json")

    with op.batch_alter_table("content_revisions") as batch_op:
        batch_op.alter_column("depot_file", postgresql_using="depot_file::json", type_=JSON)
    # ### end Alembic commands ###


def downgrade():
    pass
    # HACK - G.M -  2021-03-11 - reconvert to reduced size varchar instead of 4000
    # to be compliant with mysql/mariadb on utf8bm4
    with op.batch_alter_table("users") as batch_op:
        batch_op.alter_column("avatar", type_=VARCHAR(REDUCED_SIZE_FOR_DEPOT_STORAGE_JSON))
        batch_op.alter_column("cropped_avatar", type_=VARCHAR(REDUCED_SIZE_FOR_DEPOT_STORAGE_JSON))
        batch_op.alter_column("cover", type_=VARCHAR(REDUCED_SIZE_FOR_DEPOT_STORAGE_JSON))
        batch_op.alter_column("cropped_cover", type_=VARCHAR(REDUCED_SIZE_FOR_DEPOT_STORAGE_JSON))

    with op.batch_alter_table("content_revisions") as batch_op:
        batch_op.alter_column("depot_file", type_=VARCHAR(REDUCED_SIZE_FOR_DEPOT_STORAGE_JSON))
