"""add reset_password feature for user

Revision ID: c223cce1a413
Revises: a143b60aad61
Create Date: 2018-08-23 11:57:25.950135

"""

# revision identifiers, used by Alembic.
revision = 'c223cce1a413'
down_revision = 'a143b60aad61'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_password_token_created', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('reset_password_token_hash', sa.Unicode(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_password_token_hash')
    op.drop_column('users', 'reset_password_token_created')
    # ### end Alembic commands ###
