"""add creator to workspace

Revision ID: cd79614189ac
Revises: 32e629b17e2e
Create Date: 2019-07-10 11:04:00.497200

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "cd79614189ac"
down_revision = "32e629b17e2e"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workspaces") as batch_op:
        batch_op.add_column(sa.Column("owner_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            constraint_name="fk_workspaces_owner_id_users",
            referent_table="users",
            local_cols=["owner_id"],
            remote_cols=["user_id"],
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workspaces") as batch_op:
        batch_op.drop_constraint("fk_workspaces_owner_id_users", type_="foreignkey")
        batch_op.drop_column("owner_id")
    # ### end Alembic commands ###
