"""add_pubic_download_enabled_and_public_upload_enabled_bool_to_workspace

Revision ID: cd9f985612c5
Revises: f985419d2205
Create Date: 2019-09-04 14:12:48.345142

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "cd9f985612c5"
down_revision = "f985419d2205"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workspaces") as batch_op:
        batch_op.add_column(
            sa.Column(
                "public_download_enabled",
                sa.Boolean(),
                server_default=sa.sql.expression.literal(False),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "public_upload_enabled",
                sa.Boolean(),
                server_default=sa.sql.expression.literal(False),
                nullable=False,
            )
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workspaces") as batch_op:
        batch_op.drop_column("public_upload_enabled")
        batch_op.drop_column("public_download_enabled")
    # ### end Alembic commands ###
