"""add upload_permissions

Revision ID: eeac0cd986c1
Revises: 7b23e5ce0b6d
Create Date: 2019-08-12 11:07:28.416896

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "eeac0cd986c1"
down_revision = "7b23e5ce0b6d"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "upload_permissions",
        sa.Column("upload_permission_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("email", sa.Unicode(length=255), nullable=False),
        sa.Column("token", sa.Unicode(length=255), nullable=False),
        sa.Column("upload_permission_group_uuid", sa.Unicode(length=255), nullable=False),
        sa.Column(
            "type", sa.Enum("EMAIL", "PUBLIC_LINK", name="uploadpermissiontype"), nullable=False
        ),
        sa.Column("password", sa.Unicode(length=128), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("disabled", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_id"], ["users.user_id"], name=op.f("fk_upload_permissions_author_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.workspace_id"],
            name=op.f("fk_upload_permissions_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("upload_permission_id", name=op.f("pk_upload_permissions")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("upload_permissions")
    sa.Enum(name="uploadpermissiontype").drop(op.get_bind(), checkfirst=False)

    # ### end Alembic commands ###
