"""fix__sequence_naming_with_postgresql

Revision ID: f985419d2205
Revises: cd79614189ac
Create Date: 2019-09-03 12:06:07.824711

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "f985419d2205"
down_revision = "cd79614189ac"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_context().dialect.name == "postgresql":
        op.execute(
            "ALTER SEQUENCE upload_permissions_upload_permission_id_seq RENAME TO seq__upload_permission__permission_id;"
        )
        op.execute("CREATE SEQUENCE seq__content_shares__share_id ;")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_context().dialect.name == "postgresql":
        op.execute(
            "ALTER SEQUENCE seq__upload_permission__permission_id RENAME TO upload_permissions_upload_permission_id_seq;"
        )
        op.execute("DROP SEQUENCE seq__content_shares__share_id;")
    # ### end Alembic commands ###
