describe('navigate :: workspace > create_new > file', function () {
    before(function () {
        cy.visit('/login')
        cy.get('input[type=email]').type('admin@admin.admin')
        cy.get('input[type=password]').type('admin@admin.admin')
        cy.get('form').find('button').get('.connection__form__btnsubmit').click()
    })
    it ('dashboard > button', function() {
        cy.get('.dashboard__calltoaction .fa-paperclip').should('be.visible')
        cy.get('.dashboard__calltoaction .fa-paperclip').click()
        cy.get('.cardPopup__container').should('be.visible')
        cy.get('.cardPopup__header').should('be.visible')
        cy.get('.cardPopup__close').should('be.visible')
        cy.get('.cardPopup__body').should('be.visible')
        cy.get('.cardPopup__container .createcontent__contentname__title').should('be.visible')
        cy.get('.cardPopup__container .filecontent__form').should('be.visible')
        cy.get('.cardPopup__container .createcontent__form__button').should('be.visible')
        cy.get('.cardPopup__container .cardPopup__close').click()
        cy.get('.cardPopup__container .createcontent__contentname').should('not.be.visible')
    })
    it ('header button', function () {
        cy.get('#dropdownCreateBtn.workspace__header__btnaddcontent__label').should('be.visible')
        cy.get('#dropdownCreateBtn.workspace__header__btnaddcontent__label').click()
        cy.get('.show .subdropdown__link__file__icon').click()
        cy.get('.cardPopup__container').should('be.visible')
        cy.get('.cardPopup__header').should('be.visible')
        cy.get('.cardPopup__close').should('be.visible')
        cy.get('.cardPopup__body').should('be.visible')
        cy.get('.cardPopup__container .createcontent__contentname__title').should('be.visible')
        cy.get('.cardPopup__container .filecontent__form').should('be.visible')
        cy.get('.cardPopup__container .createcontent__form__button').should('be.visible')
        cy.get('.cardPopup__container .cardPopup__close').click()
        cy.get('.cardPopup__container .createcontent__contentname').should('not.be.visible')
    })
    it ('content button', function () {
        cy.get('.workspace__content__button.dropdownCreateBtn .__label').should('be.visible')
        cy.get('.workspace__content__button.dropdownCreateBtn .__label').click()
        cy.get('.show .subdropdown__link__file__icon').click()
        cy.get('.cardPopup__container').should('be.visible')
        cy.get('.cardPopup__header').should('be.visible')
        cy.get('.cardPopup__close').should('be.visible')
        cy.get('.cardPopup__body').should('be.visible')
        cy.get('.cardPopup__container .createcontent__contentname__title').should('be.visible')
        cy.get('.cardPopup__container .filecontent__form').should('be.visible')
        cy.get('.cardPopup__container .createcontent__form__button').should('be.visible')
        cy.get('.cardPopup__container .cardPopup__close').click()
        cy.get('.cardPopup__container .createcontent__contentname').should('not.be.visible')
    })
})
