describe('operation :: workspace > delete > thread', function () {
    before(function () {
        cy.visit('/login')
        cy.get('input[type=email]').type('admin@admin.admin')
        cy.get('input[type=password]').type('admin@admin.admin')
        cy.get('form').find('button').get('.connection__form__btnsubmit').click()
    })
    it ('all content > thread > delete first thread', function(){
        cy.get('.sidebar__content__navigation__workspace__item__submenu > li:nth-child(2)').click()
        cy.get('.pageTitleGeneric__title__icon').should('be.visible')
        cy.get('.content__name__text').contains('thread').should('be.visible')
        cy.get('.content__name__text').contains('thread').click()
        cy.get('#appFeatureContainer .thread.visible').should('be.visible')
        cy.get('.align-items-center button:nth-child(2)').click()
        cy.get('#appFeatureContainer .timeline__info__btnrestore').should('be.visible')
        cy.get('.thread__contentpage__header__close').click()
        cy.get('#appFeatureContainer .thread.visible').should('not.be.visible')
        cy.get('.content__name__text').contains('thread').should('not.be.visible')
    })
    it ('all content > thread > delete second thread', function(){
        cy.get('.sidebar__content__navigation__workspace__item__submenu > li:nth-child(2)').click()
        cy.get('.pageTitleGeneric__title__icon').should('be.visible')
        cy.get('.content__name__text').contains('thread1').should('be.visible')
        cy.get('.content__name__text').contains('thread1').click()
        cy.get('#appFeatureContainer .thread.visible').should('be.visible')
        cy.get('.align-items-center button:nth-child(2)').click()
        cy.get('#appFeatureContainer .timeline__info__btnrestore').should('be.visible')
        cy.get('.thread__contentpage__header__close').click()
        cy.get('#appFeatureContainer .thread.visible').should('not.be.visible')
        cy.get('.content__name__text').contains('thread1').should('not.be.visible')
    })
})