"""user_timezone

Revision ID: 2cd20ff3d23a
Revises: b4b8d57b54e5
Create Date: 2016-11-08 11:32:00.903232

"""

# revision identifiers, used by Alembic.
revision = '2cd20ff3d23a'
down_revision = 'b4b8d57b54e5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('timezone', sa.Unicode(length=255), server_default='', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone')
    ### end Alembic commands ###
