"""Add calendar_enabled column to Workspace

Revision ID: 534c4594ed29
Revises: da12239d9da0
Create Date: 2016-05-31 13:02:28.301984

"""

# revision identifiers, used by Alembic.
revision = '534c4594ed29'
down_revision = 'da12239d9da0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('calendar_enabled', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'calendar_enabled')
    ### end Alembic commands ###
