"""User auth token columns

Revision ID: bdb195ed95bb
Revises: 534c4594ed29
Create Date: 2016-07-28 15:38:18.889151

"""

# revision identifiers, used by Alembic.
revision = 'bdb195ed95bb'
down_revision = '534c4594ed29'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_token', sa.Unicode(length=255), nullable=True))
    op.add_column('users', sa.Column('auth_token_created', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auth_token_created')
    op.drop_column('users', 'auth_token')
    ### end Alembic commands ###
