---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: python
    tag: ((python_version))-stretch
inputs:
  - name: tracim
run:
  dir: tracim
  path: ((path))
  args: [((database))]
