---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: algooci/tracim
inputs:
  - name: tracim
run:
  dir: tracim
  path: concourse/scripts/run_with_python
  args: [((python_version)), ((path)), ((database))]
