---
# Generic task for running a Tracim test script
# It requires 3 variables to work:
#  - path: path to the test script
#  - python_version : version to use for running the given test script
#  - database : database to use for running the given test script. can be "" for tests not using this parameter
# It also needs a "tracim" input which should be the root of tracim repository.
platform: linux
image_resource:
  type: registry-image
  source:
    repository: algooci/tracim
inputs:
  - name: tracim
run:
  dir: tracim
  path: concourse/scripts/run_test_script
  # TODO - S.G - 2021-08-04 - find a way to give generic args through a concourse variable
  args: [((python_version)), ((path)), ((database))]
