# Error code format : [TYPE:2c]-[NUMBER:2c]
# TYPE:
# NF=Not found error
# RI=Right error
# VA=validation post-marshallow
# CO=Conflict error
# AT=Auth error
# MV = marshmallow schema validation error

ERROR_CODE_GENERIC_SCHEMA_VALIDATION_ERROR = 'SV-01'
# Tracim Not found Error
ERROR_CODE_USER_NOT_FOUND = 'NF-01'
ERROR_CODE_WORKSPACE_NOT_FOUND = 'NF-02'
ERROR_CODE_CONTENT_NOT_FOUND = 'NF-03'
# Preview Based
ERROR_CODE_UNAIVALABLE_PREVIEW_TYPE = 'NF-11'
ERROR_CODE_PAGE_OF_PREVIEW_NOT_FOUND = 'NF-12'
ERROR_CODE_UNAIVALABLE_PREVIEW = 'NF-13'

# Right Error
ERROR_CODE_INSUFFICIENT_USER_PROFILE = 'RI-01'
ERROR_CODE_INSUFFICIENT_USER_ROLE_IN_WORKSPACE = 'RI-02'

# Auth Error
ERROR_CODE_NOT_AUTHENTICATED = 'AT-01'
ERROR_CODE_USER_NOT_ACTIVE = 'AT-02'
ERROR_CODE_AUTHENTICATION_FAILED = 'AT-03'

# Validation Error
# Not in Tracim Request #
ERROR_CODE_USER_NOT_IN_TRACIM_REQUEST = 'VA-01'
ERROR_CODE_WORKSPACE_NOT_IN_TRACIM_REQUEST = 'VA-02'
ERROR_CODE_CONTENT_NOT_IN_TRACIM_REQUEST = 'VA-03'
# Invalid ID #
ERROR_CODE_USER_INVALID_USER_ID = 'VA-11'
ERROR_CODE_WORKSPACE_INVALID_ID = 'VA-12'
ERROR_CODE_CONTENT_INVALID_ID = 'VA-13'
ERROR_CODE_COMMENT_INVALID_ID = 'VA-14'

# Other #
ERROR_CODE_CONTENT_TYPE_NOT_ALLOWED = 'VA-21'
ERROR_CODE_WORKSPACE_DO_NOT_MATCH = 'VA-22'
ERROR_CODE_PREVIEW_DIM_NOT_ALLOWED = 'VA-23'
ERROR_CODE_WRONG_USER_PASSWORD = 'VA-24'
ERROR_CODE_PASSWORD_DO_NOT_MATCH = 'VA-25'
ERROR_CODE_EMAIL_ALREADY_EXIST_IN_DB = 'VA-26'
ERROR_CODE_EMAIL_VALIDATION_FAILED = 'VA-27'
ERROR_CODE_EMAIL_UNALLOWED_SUBCONTENT = 'VA-28'
ERROR_CODE_INVALID_RESET_PASSWORD_TOKEN = 'VA-29'
ERROR_CODE_EXPIRED_RESET_PASSWORD_TOKEN = 'VA-30'
ERROR_CODE_PARENT_NOT_FOUND = 'VA-31'
ERROR_CODE_SAME_VALUE_ERROR = 'VA-32'

# Conflict Error
ERROR_CODE_USER_ALREADY_EXIST = 'CO-01'
ERROR_CODE_CONTENT_LABEL_ALREADY_USED_THERE = 'CO-02'
