# Error code format
# 1xxx: not found error
# 2xxx: validation error
# 3xxx: conflict error
# 4xxx: authentication and authorization
# 9xxx: core errors(family of error code reserved
# for unclassable errors or very low level errors)


# Tracim Not found Error
USER_NOT_FOUND = 1001
WORKSPACE_NOT_FOUND = 1002
CONTENT_NOT_FOUND = 1003
PARENT_NOT_FOUND = 1004
# Preview Based
UNAVAILABLE_PREVIEW_TYPE = 1011
PAGE_OF_PREVIEW_NOT_FOUND = 1012
UNAIVALABLE_PREVIEW = 1013

# Validation Error
GENERIC_SCHEMA_VALIDATION_ERROR = 2001
# Not in Tracim Request #
USER_NOT_IN_TRACIM_REQUEST = 2011
WORKSPACE_NOT_IN_TRACIM_REQUEST = 2012
CONTENT_NOT_IN_TRACIM_REQUEST = 2013
# Invalid ID #
USER_INVALID_USER_ID = 2021
WORKSPACE_INVALID_ID = 2022
CONTENT_INVALID_ID = 2023
COMMENT_INVALID_ID = 2024

# Other #
CONTENT_TYPE_NOT_ALLOWED = 2031
WORKSPACE_DO_NOT_MATCH = 2032
PREVIEW_DIM_NOT_ALLOWED = 2033
WRONG_USER_PASSWORD = 2034
PASSWORD_DO_NOT_MATCH = 2035
EMAIL_ALREADY_EXIST_IN_DB = 2036
EMAIL_VALIDATION_FAILED = 2037
EMAIL_UNALLOWED_SUBCONTENT = 2038
INVALID_RESET_PASSWORD_TOKEN = 2039
EXPIRED_RESET_PASSWORD_TOKEN = 2040
SAME_VALUE_ERROR = 2041
USER_NOT_ACTIVE = 2042
USER_DELETED = 2043

# Conflict Error
USER_ALREADY_EXIST = 3001
CONTENT_LABEL_ALREADY_USED_THERE = 3002
USER_CANT_DISABLE_ITSELF = 3003

# Auth Error
AUTHENTICATION_FAILED = 4001
# Right Error
INSUFFICIENT_USER_PROFILE = 4002
INSUFFICIENT_USER_ROLE_IN_WORKSPACE = 4003
ACTION_UNAUTHORIZED_ON_AUTH_USER_HIMSELF = 4004
